major fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,23 +21,24 @@ jobs:
       - run:
           name: build-and-host-engine
           environment:
-            JIRA_STORY: 0.0.0
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
           command: |
             if [ "$CIRCLE_BRANCH" != "master" ]; then
               PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
               PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PROJECT_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
               JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-              sed -i "s/^version:.*/version: 0.0.0$JIRA_STORY-SNAPSHOT/" helm/ph-ee-engine/Chart.yaml
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
             fi
+            sed -i "s/^version:.*/version: 0.0.0$JIRA_STORY-SNAPSHOT/" helm/ph-ee-engine/Chart.yaml
             helm dep up helm/ph-ee-engine
             helm package helm/ph-ee-engine
             helm repo index .
             echo "$CERT_FILE" | base64 --decode > b64encoded.pem
             chmod 400 b64encoded.pem
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT
             scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT.tgz ec2-user@13.233.68.128:~/
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo cp -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT index.yaml ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT.tgz
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo cp -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT index.yaml ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT.tgz
   build-and-host-g2p-sandbox:
     docker:
       - image: cimg/python:3.10
@@ -52,23 +53,27 @@ jobs:
       - run:
           name: build-and-host-g2p-sandbox
           environment:
-            JIRA_STORY: 0.0.0
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
           command: |
             if [ "$CIRCLE_BRANCH" != "master" ]; then
               PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
               PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
               JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-              sed -i "s/^version:.*/version: 0.0.0$JIRA_STORY/" helm/g2p-sandbox/Chart.yaml
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
+              
             fi
+            sed -i "s/^version:.*/version: 0.0.0$JIRA_STORY/" helm/g2p-sandbox/Chart.yaml
+            sed -i '5s/.*/repository: https://fynarfin.io/images$JIRA_STORY_DIR/ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT/' helm/g2p-sandbox/Chart.yaml
+            sed -i '6s/.*/version: 0.0.0$JIRA_STORY-SNAPSHOT' helm/g2p-sandbox/Chart.yaml
             helm dep up helm/g2p-sandbox
             helm package helm/g2p-sandbox
             helm repo index .
             echo "$CERT_FILE" | base64 --decode > b64encoded.pem
             chmod 400 b64encoded.pem
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-g2psandbox-0.0.0$JIRA_STORY
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-0.0.0$JIRA_STORY
             scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-0.0.0$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-g2psandbox-0.0.0$JIRA_STORY index.yaml ph-ee-g2psandbox-0.0.0$JIRA_STORY.tgz
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-0.0.0$JIRA_STORY index.yaml ph-ee-g2psandbox-0.0.0$JIRA_STORY.tgz
   build-host-g2p-fyn-chart:
     docker:
       - image: cimg/python:3.10
@@ -84,24 +89,27 @@ jobs:
       - run:
           name: build-host-g2p-fyn-chart
           environment:
-            JIRA_STORY: 0.0.0
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
           command: |
             if [ "$CIRCLE_BRANCH" != "master" ]; then
               PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
               PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
               JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-              sed -i "s/^version:.*/version: 0.2.0$JIRA_STORY/" ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
             fi
+            sed -i "s/^version:.*/version: 0.2.0$JIRA_STORY/" ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+            sed -i '11s/.*/repository: https://fynarfin.io/images$JIRA_STORY_DIR/ph-ee-g2psandbox-0.0.0JIRA_STORY/' ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+            sed -i '12s/.*/version: 0.0.0$JIRA_STORY' ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
             cat ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
             helm dep up ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT
             helm package ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT
             helm repo index .
             echo "$CERT_FILE" | base64 --decode > b64encoded.pem
             chmod 400 b64encoded.pem
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY
             scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-g2psandbox-fynarfin-0.2.0-$JIRA_STORY index.yaml ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY.tgz
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-fynarfin-0.2.0-$JIRA_STORY index.yaml ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY.tgz
   build-and-host-g2p-sandbox-security:
     docker:
       - image: cimg/python:3.10
@@ -116,16 +124,18 @@ jobs:
       - run:
           name: build-and-host-g2p-sandbox-security
           environment:
-            JIRA_STORY: 0.0.0
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
           command: |
             if [ "$CIRCLE_BRANCH" != "master" ]; then
               PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
               PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
               JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-              sed -i "s/^version:.*/version: 0.2.0-$JIRA_STORY/" helm/g2p-sandbox-security/Chart.yaml
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
             fi
-            sed -i '7s/.*/version: 0.0.0$JIRA_STORY/' helm/g2p-sandbox-security/Chart.yaml
+            sed -i "s/^version:.*/version: 0.0.0$JIRA_STORY/" helm/g2p-sandbox-security/Chart.yaml
+            sed -i '10s/.*/repository: https://fynarfin.io/images$JIRA_STORY_DIR/ph-ee-engine-0.0.0$JIRA_STORY-SNAPSHOT/' helm/g2p-sandbox-security/Chart.yaml
+            sed -i '11s/.*/version: 0.0.0$JIRA_STORY-SNAPSHOT' helm/g2p-sandbox-security/Chart.yaml
             # - run: "sed -i '4s/.*/version: 0.0.0-SNAPSHOT/' helm/g2p-sandbox-security/requirements.yaml"
             # SED & replace dependency with 0.0.0
             helm dep up helm/g2p-sandbox-security
@@ -133,9 +143,9 @@ jobs:
             helm repo index .
             echo "$CERT_FILE" | base64 --decode > b64encoded.pem
             chmod 400 b64encoded.pem
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-g2psandbox-security$JIRA_STORY
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-security$JIRA_STORY
             scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-security-0.0.0$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
-            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/jira-story-version/ph-ee-g2psandbox-security$JIRA_STORY index.yaml ph-ee-g2psandbox-security-0.0.0$JIRA_STORY.tgz
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-security$JIRA_STORY index.yaml ph-ee-g2psandbox-security-0.0.0$JIRA_STORY.tgz
   docker-image-availability-check-and-upgrade:
     docker:
       - image: cimg/python:3.10
