[PHEE-490] Publish helm chart with jira ticket from circleci (#302)
* chart fix for jira story

* fix path issue

* major fix

* test

* test

* fix

* test

* tst

* fix sed issuye

* fix in sed with @

* test

* ttest

* fs

* tes

* tes

* tet

* change workflow

* test

* ddf

* No imput file

* test

* asdb

* tes

* done

* fix

* test

* orb changed

* removed chart and add repo field from orb

* fix for chart url

* final test

* test

* fix helm upgrade issue

* fix helm upgrade issue

* remove jira-tag as latest

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,15 +18,28 @@ jobs:
       - run: rm -f helm/ph-ee-engine/Chart.lock helm/ph-ee-engine/requirements.lock helm/ph-ee-engine/charts/*
       - helm/install-helm-client:
           version: "v3.8.2"
-      - run: "sed -i '2s/.*/appVersion: 0.0.0/' helm/ph-ee-engine/Chart.yaml"
-      - run: "sed -i '5s/.*/version: 0.0.0-SNAPSHOT/' helm/ph-ee-engine/Chart.yaml"
-      - run: helm dep up helm/ph-ee-engine
-      - run: helm package helm/ph-ee-engine
-      - run: helm repo index .
-      - run: echo "$CERT_FILE" | base64 --decode > b64encoded.pem
-      - run: chmod 400 b64encoded.pem
-      - run: scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-engine-0.0.0-SNAPSHOT.tgz ec2-user@13.233.68.128:~/
-      - run: ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo cp -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/ph-ee-engine-0.0.0-SNAPSHOT index.yaml ph-ee-engine-0.0.0-SNAPSHOT.tgz
+      - run:
+          name: build-and-host-engine
+          environment:
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
+          command: |
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PROJECT_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
+              echo Charts will save in https://fynarfin.io/images$JIRA_STORY_DIR
+            fi
+            sed -i "5s/.*/version: 0.0.0-SNAPSHOT$JIRA_STORY/" helm/ph-ee-engine/Chart.yaml
+            helm dep up helm/ph-ee-engine
+            helm package helm/ph-ee-engine
+            helm repo index .
+            echo "$CERT_FILE" | base64 --decode > b64encoded.pem
+            chmod 400 b64encoded.pem
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-engine$JIRA_STORY
+            scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-engine-0.0.0-SNAPSHOT$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo cp -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-engine$JIRA_STORY index.yaml ph-ee-engine-0.0.0-SNAPSHOT$JIRA_STORY.tgz
   build-and-host-g2p-sandbox:
     docker:
       - image: cimg/python:3.10
@@ -38,17 +51,30 @@ jobs:
       - run: rm -f helm/g2p-sandbox/Chart.lock helm/g2p-sandbox/requirements.lock helm/g2p-sandbox/charts/*
       - helm/install-helm-client:
           version: "v3.8.2"
-      - run: "sed -i '6s/.*/appVersion: 0.0.0/' helm/g2p-sandbox/Chart.yaml"
-      - run: "sed -i '7s/.*/version: 0.0.0/' helm/g2p-sandbox/Chart.yaml" 
-      # - run: "sed -i '4s/.*/version: 0.0.0-SNAPSHOT/' helm/g2p-sandbox/requirements.yaml"
-      # SED & replace dependency with 0.0.0
-      - run: helm dep up helm/g2p-sandbox
-      - run: helm package helm/g2p-sandbox
-      - run: helm repo index .
-      - run: echo "$CERT_FILE" | base64 --decode > b64encoded.pem
-      - run: chmod 400 b64encoded.pem
-      - run: scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-0.0.0.tgz ec2-user@13.233.68.128:~/
-      - run: ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/ph-ee-g2psandbox-0.0.0 index.yaml ph-ee-g2psandbox-0.0.0.tgz
+      - run:
+          name: build-and-host-g2p-sandbox
+          environment:
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
+          command: |
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
+            fi
+            sed -i "5s/.*/version: 0.0.0$JIRA_STORY/" helm/g2p-sandbox/Chart.yaml
+            sed -i "10s@^ *repository:.*\$@  repository: https://fynarfin.io/images$JIRA_STORY_DIR/ph-ee-engine$JIRA_STORY@" helm/g2p-sandbox/Chart.yaml
+            sed -i "11s@^ *version:.*\$@  version: 0.0.0-SNAPSHOT$JIRA_STORY@" helm/g2p-sandbox/Chart.yaml
+            cat helm/g2p-sandbox/Chart.yaml
+            helm dep up helm/g2p-sandbox
+            helm package helm/g2p-sandbox
+            helm repo index .
+            echo "$CERT_FILE" | base64 --decode > b64encoded.pem
+            chmod 400 b64encoded.pem
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox$JIRA_STORY
+            scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-0.0.0$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox$JIRA_STORY index.yaml ph-ee-g2psandbox-0.0.0$JIRA_STORY.tgz
   build-host-g2p-fyn-chart:
     docker:
       - image: cimg/python:3.10
@@ -61,14 +87,30 @@ jobs:
       - helm/install-helm-client:
           version: "v3.8.2"
       # - run: "sed -i '12s/.*/version: 0.0.0/' helm/g2p-sandbox-fynarfin-SIT/Chart.yaml"
-      - run: cat ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
-      - run: helm dep up ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT
-      - run: helm package ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT
-      - run: helm repo index .
-      - run: echo "$CERT_FILE" | base64 --decode > b64encoded.pem
-      - run: chmod 400 b64encoded.pem
-      - run: scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-fynarfin-0.2.0.tgz ec2-user@13.233.68.128:~/
-      - run: ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/ph-ee-g2psandbox-fynarfin index.yaml ph-ee-g2psandbox-fynarfin-0.2.0.tgz    
+      - run:
+          name: build-host-g2p-fyn-chart
+          environment:
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
+          command: |
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
+            fi
+            sed -i "6s/.*/version: 0.2.0$JIRA_STORY/" ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+            sed -i "11s@^ *repository:.*\$@  repository: https://fynarfin.io/images$JIRA_STORY_DIR/ph-ee-g2psandbox$JIRA_STORY@" ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+            sed -i "12s@^ *version:.*\$@  version: 0.0.0$JIRA_STORY@" ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+            cat ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT/Chart.yaml
+            helm dep up ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT
+            helm package ph-ee-env-labs/helm/g2p-sandbox-fynarfin-SIT
+            helm repo index .
+            echo "$CERT_FILE" | base64 --decode > b64encoded.pem
+            chmod 400 b64encoded.pem
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-fynarfin$JIRA_STORY
+            scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-fynarfin$JIRA_STORY index.yaml ph-ee-g2psandbox-fynarfin-0.2.0$JIRA_STORY.tgz
   build-and-host-g2p-sandbox-security:
     docker:
       - image: cimg/python:3.10
@@ -80,27 +122,46 @@ jobs:
       - run: rm -f helm/g2p-sandbox-security/Chart.lock helm/g2p-sandbox-security/requirements.lock helm/g2p-sandbox-security/charts/*
       - helm/install-helm-client:
           version: "v3.8.2"
-      - run: "sed -i '6s/.*/appVersion: 0.0.0/' helm/g2p-sandbox-security/Chart.yaml"
-      - run: "sed -i '7s/.*/version: 0.0.0/' helm/g2p-sandbox-security/Chart.yaml" 
-      # - run: "sed -i '4s/.*/version: 0.0.0-SNAPSHOT/' helm/g2p-sandbox-security/requirements.yaml"
-      # SED & replace dependency with 0.0.0
-      - run: helm dep up helm/g2p-sandbox-security
-      - run: helm package helm/g2p-sandbox-security
-      - run: helm repo index .
-      - run: echo "$CERT_FILE" | base64 --decode > b64encoded.pem
-      - run: chmod 400 b64encoded.pem
-      - run: ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images/ph-ee-g2psandbox-security
-      - run: scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-security-0.0.0.tgz ec2-user@13.233.68.128:~/
-      - run: ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images/ph-ee-g2psandbox-security index.yaml ph-ee-g2psandbox-security-0.0.0.tgz
+      - run:
+          name: build-and-host-g2p-sandbox-security
+          environment:
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
+          command: |
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=-$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
+            fi
+            sed -i "5s/.*/version: 0.0.0$JIRA_STORY/" helm/g2p-sandbox-security/Chart.yaml
+            sed -i "10s@^ *repository:.*\$@  repository: https://fynarfin.io/images$JIRA_STORY_DIR/ph-ee-engine$JIRA_STORY@" helm/g2p-sandbox-security/Chart.yaml
+            sed -i "11s@^ *version:.*\$@  version: 0.0.0-SNAPSHOT$JIRA_STORY@" helm/g2p-sandbox-security/Chart.yaml
+            cat helm/g2p-sandbox-security/Chart.yaml
+            # - run: "sed -i '4s/.*/version: 0.0.0-SNAPSHOT/' helm/g2p-sandbox-security/requirements.yaml"
+            # SED & replace dependency with 0.0.0
+            helm dep up helm/g2p-sandbox-security
+            helm package helm/g2p-sandbox-security
+            helm repo index .
+            echo "$CERT_FILE" | base64 --decode > b64encoded.pem
+            chmod 400 b64encoded.pem
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mkdir -p /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-security$JIRA_STORY
+            scp -o StrictHostKeyChecking=No -i b64encoded.pem index.yaml ph-ee-g2psandbox-security-0.0.0$JIRA_STORY.tgz ec2-user@13.233.68.128:~/
+            ssh -i b64encoded.pem -o StrictHostKeyChecking=No ec2-user@13.233.68.128 sudo mv -t /apps/apache-tomcat-7.0.82/webapps/ROOT/images$JIRA_STORY_DIR/ph-ee-g2psandbox-security$JIRA_STORY index.yaml ph-ee-g2psandbox-security-0.0.0$JIRA_STORY.tgz
   docker-image-availability-check-and-upgrade:
     docker:
       - image: cimg/python:3.10
+    environment:
+      TERM: dumb
     steps:
       - mifos-orb/docker-image-availability-check-and-upgrade:
           namespace: paymenthub
-          chart: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin/ph-ee-g2psandbox-fynarfin-0.2.0.tgz"
+          chart-base-url: https://fynarfin.io/images
+          chart-name: ph-ee-g2psandbox-fynarfin
+          chart-version: 0.2.0
+#          chart: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin/ph-ee-g2psandbox-fynarfin-0.2.0.tgz"
           release-name: g2p-sandbox
-          add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
+#          add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
           cluster-name: "sit"
           aws-region: "$REGION"
           service-file-path: https://raw.githubusercontent.com/openMF/ph-ee-env-labs/master/.circleci/services.txt
diff --git a/.circleci/docker-image-availability-check-and-upgrade.yml b/.circleci/docker-image-availability-check-and-upgrade.yml
--- a/.circleci/docker-image-availability-check-and-upgrade.yml
+++ b/.circleci/docker-image-availability-check-and-upgrade.yml
@@ -7,23 +7,10 @@ orbs:
 commands:
   docker-image-availability-check-and-upgrade:
     parameters:
-      add-repo:
-        description: |
-          The url for the helm chart repository used as part of helm repo add
-          command
-        type: string
       namespace:
         default: ""
         description: |
           The kubernetes namespace that should be used.
-        type: string
-      chart:
-        default: ""
-        description: |
-          Specify for upgrade a chart reference (e.g. stable/mariadb),
-          or a path to a packaged chart (e.g. ./nginx-1.2.3.tgz),
-          or a path to an unpacked chart directory (e.g. ./nginx)
-          or an absolute URL (e.g. https://example.com/charts/nginx-1.2.3.tgz)
         type: string
       release-name:
         default: ""
@@ -39,6 +26,15 @@ commands:
       service-file-path:
         default: https://raw.githubusercontent.com/openMF/ph-ee-env-labs/master/.circleci/services.txt
         type: string
+      chart-base-url:
+        default: https://fynarfin.io/images
+        type: string
+      chart-name:
+        default: ph-ee-g2psandbox-fynarfin
+        type: string
+      chart-version:
+        default: 0.2.0
+        type: string
 
     steps:
       - checkout
@@ -50,47 +46,50 @@ commands:
       - run:
           name: fetch docker images and helm upgrade
           environment:
-            ORB_PARAM_CHART: << parameters.chart >>
+            ORB_CHART_BASE_URL: << parameters.chart-base-url >>
+            ORB_CHART_NAME: << parameters.chart-name >>
+            ORB_CHART_VERSION: << parameters.chart-version >>
             ORB_PARAM_NAMESPACE: << parameters.namespace >>
             ORB_PARAM_RELEASE_NAME: << parameters.release-name >>
-            ORB_PARAM_REPO: << parameters.add-repo >>
+            JIRA_STORY: ''
+            JIRA_STORY_DIR: ''
             VALUES_TO_OVERRIDE: ''
             SERVICE_FILE_PATH: << parameters.service-file-path>>
           command: |
-            if [ "$CIRCLE_BRANCH" != "master" ]; then
-              
-              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
-              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
-              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-              
-              
-              function get_services_from_file() {
+            function get_services_from_file() {
                 file=$1
                 while IFS= read -r line || [ -n "$line" ]; do
                   echo "Processing line: $line"
                   generate_values_to_override $line
                 done < "$file"
-              }
+            }
             
-              function generate_values_to_override() {
-                PREFIX="docker.io/"
-                if check_for_image_tag ${2#"$PREFIX"} ${JIRA_STORY}; then
-                    echo "$1=$2:$JIRA_STORY"
-                    VALUES_TO_OVERRIDE+=$(echo "$1=$2:$JIRA_STORY"),
-                fi
-              }
-              function check_for_image_tag(){
-                echo "checking for service with image tag $1 $2"
-                curl --silent -f --head -lL https://hub.docker.com/v2/repositories/$1/tags/$2/ > /dev/null
-              }
+            function generate_values_to_override() {
+              PREFIX="docker.io/"
+              if check_for_image_tag ${2#"$PREFIX"} ${JIRA_STORY}; then
+                  echo "$1=$2:$JIRA_STORY"
+                  VALUES_TO_OVERRIDE+=$(echo "$1=$2:$JIRA_STORY"),
+              else
+                  VALUES_TO_OVERRIDE+=$(echo "$1=$2:latest"),
+              fi
+            }
+            function check_for_image_tag(){
+              echo "checking for service with image tag $1 $2"
+              curl --silent -f --head -lL https://hub.docker.com/v2/repositories/$1/tags/$2/ > /dev/null
+            }
+            if [ "$CIRCLE_BRANCH" != "master" ]; then
               
-              echo $SERVICE_FILE_PATH
-              wget $SERVICE_FILE_PATH
-              filename=$(basename "$SERVICE_FILE_PATH")
-              get_services_from_file $filename
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY" && JIRA_STORY_DIR=$(echo /jira-story-version); fi
             fi 
-              
+            
+            echo $SERVICE_FILE_PATH
+            wget $SERVICE_FILE_PATH
+            filename=$(basename "$SERVICE_FILE_PATH")
+            get_services_from_file $filename
+            
             if [ -n "${VALUES_TO_OVERRIDE}" ]; then
                 VALUES_TO_OVERRIDE=$(echo --set ${VALUES_TO_OVERRIDE::-1})
                 echo "VALUES_TO_OVERRIDE: $VALUES_TO_OVERRIDE"
@@ -99,7 +98,18 @@ commands:
             if [ -n "${ORB_PARAM_NAMESPACE}" ]; then
                 ORB_PARAM_NAMESPACE=$(echo --namespace ${ORB_PARAM_NAMESPACE})
             fi
+            if [ -n "${JIRA_STORY}" ]; then
+              JIRA_STORY=-$(echo $JIRA_STORY)
+            fi
             
+            # Generating the chart url for deployment
+            # chart: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin/ph-ee-g2psandbox-fynarfin-0.2.0.tgz"
+            
+            ORB_PARAM_CHART=$(echo "$ORB_CHART_BASE_URL$JIRA_STORY_DIR/$ORB_CHART_NAME$JIRA_STORY/$ORB_CHART_NAME-$ORB_CHART_VERSION$JIRA_STORY.tgz")
+            
+            # add-repo: "https://fynarfin.io/images/ph-ee-g2psandbox-fynarfin"
+            
+            ORB_PARAM_REPO=$(echo "$ORB_CHART_BASE_URL$JIRA_STORY_DIR/$ORB_CHART_NAME$JIRA_STORY")
             echo helm repo add "${ORB_PARAM_RELEASE_NAME}" "${ORB_PARAM_REPO}"
             helm repo add "${ORB_PARAM_RELEASE_NAME}" "${ORB_PARAM_REPO}"
 
@@ -115,12 +125,7 @@ jobs:
       namespace:
         type: string
         default: ""
-      add-repo:
-        type: string
       release-name:
-        default: ""
-        type: string
-      chart:
         default: ""
         type: string
       cluster-name:
@@ -132,13 +137,23 @@ jobs:
       service-file-path:
         default: https://raw.githubusercontent.com/openMF/ph-ee-env-labs/master/.circleci/services.txt
         type: string
+      chart-base-url:
+        default: https://fynarfin.io/images/
+        type: string
+      chart-name:
+        default: ph-ee-g2psandbox-fynarfin
+        type: string
+      chart-version:
+        default: 0.2.0
+        type: string
 
     steps:
       - docker-image-availability-check-and-upgrade:
           namespace: <<parameters.namespace>>
-          add-repo: <<parameters.add-repo>>
           release-name: <<parameters.release-name>>
-          chart: <<parameters.chart>>
           cluster-name: <<parameters.cluster-name>>
           aws-region: <<parameters.aws-region>>
+          chart-base-url: https://fynarfin.io/images/
+          chart-name: ph-ee-g2psandbox-fynarfin
+          chart-version: 0.2.0
 
