test

diff --git a/.circleci/docker-image-availability-check-and-upgrade.yml b/.circleci/docker-image-availability-check-and-upgrade.yml
--- a/.circleci/docker-image-availability-check-and-upgrade.yml
+++ b/.circleci/docker-image-availability-check-and-upgrade.yml
@@ -68,14 +68,12 @@ commands:
             VOUCHERS: ph-ee-g2psandbox.ph-ee-engine.vouchers.image=docker.io/openmf/ph-ee-vouchers:latest
           command: |
             if [ "$CIRCLE_BRANCH" != "master" ]; then
+            
               PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
-              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/ph-ee-importer-rdbms/pulls/$PR_NUMBER" | jq -r '.title')
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/openmf/ph-ee-env-template/pulls/$PR_NUMBER" | jq -r '.title')
               JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1)
-              if [ -n "${JIRA_STORY}" ]; then
-                echo INVALID PR TITLE
-                exit 1;
-              fi
-              echo TICKET NO: ${JIRA_STORY}
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+              
               function docker_tag_exists() {
                 curl --silent -f --head -lL https://hub.docker.com/v2/repositories/$1/tags/$2/ > /dev/null
               }
